import Config

config :supavisor, Supavisor.Services.LocalModels, enabled: true
# Configure your database
config :supavisor, Supavisor.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  port: 5432,
  database: "supavisor_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :supavisor, SupavisorWeb.AdminProvisioning,
  enabled: true,
  provisioner: [
    username: "postgres",
    password: "postgres",
    database: "postgres",
    ssl: false,
    ssl_opts: []
  ],
  allowed_targets: [{"localhost", 5432}, {"127.0.0.1", 5432}]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use Tailwind
# for CSS and esbuild for the LiveView client JS.
config :supavisor, SupavisorWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: System.get_env("PORT", "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  watchers: [
    tailwind: {Tailwind, :install_and_run, [:supavisor, ~w(--watch)]},
    esbuild: {Esbuild, :install_and_run, [:supavisor, ~w(--sourcemap=inline --watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :supavisor, SupavisorWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"lib/supavisor_web/(live|views|components|controllers)/.*(ex)$",
      ~r"lib/supavisor_web/templates/.*(eex|heex)$"
    ]
  ]

# Configures Elixir's Logger
config :logger, :console,
  format: "$time [$level] $message $metadata\n",
  level: :debug,
  # level: :notice,
  metadata: [
    :error_code,
    :file,
    :line,
    :pid,
    :project,
    :user,
    :mode,
    :type,
    :app_name,
    :peer_ip,
    :local,
    :proxy
  ]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix,
  stacktrace_depth: 20,
  serve_endpoints: true,
  persistent: true

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# disable caching to ensure the rendered spec is refreshed
config :open_api_spex, :cache_adapter, OpenApiSpex.Plug.NoneCache
